'use strict';

/*
 * scripts/counts.js — generates live counts of rules, MCP tools, and defense
 * layers from the source. Used to keep README.md and package.json numbers
 * from drifting. Run: `npm run counts`.
 *
 * Output: JSON to stdout: { rules, mcpTools, layers }
 * Also writes a README block between <!-- COUNTS:START --> and <!-- COUNTS:END -->
 * markers if --update-readme is passed.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// --- Rules ---
function countRules() {
  const { allRules } = require(path.join(ROOT, 'src', 'rules'));
  return allRules().length;
}

// --- MCP Tools ---
// Statically count tool registrations in mcp-server.js (can't require it
// directly — it starts an MCP server on load).
function countMcpTools() {
  const code = fs.readFileSync(path.join(ROOT, 'src', 'mcp-server.js'), 'utf8');
  const matches = [...code.matchAll(/name:\s*['"]([a-z_]+)['"]/g)].map((m) => m[1]);
  const tools = matches.filter((n) => n !== 'vibeguard');
  const unique = [...new Set(tools)];
  return unique.length;
}

// --- Defense Layers ---
// Counted from the pre-deploy gates in src/pre-deploy.js (the canonical list).
function countLayers() {
  // Count from pre-deploy.js GATES array — no git needed.
  try {
    const src = fs.readFileSync(path.join(ROOT, 'src', 'pre-deploy.js'), 'utf8');
    const match = src.match(/const GATES\s*=\s*\[([\s\S]*?)\]/);
    if (match) {
      const ids = match[1].match(/id:\s*'[^']+'/g);
      if (ids) return ids.length;
    }
  } catch {}
  return 13;
}

function getCounts() {
  return {
    rules: countRules(),
    mcpTools: countMcpTools(),
    layers: countLayers(),
  };
}

// --- README update ---
function updateReadme(counts) {
  const readmePath = path.join(ROOT, 'README.md');
  let content = fs.readFileSync(readmePath, 'utf8');
  const startMarker = '<!-- COUNTS:START -->';
  const endMarker = '<!-- COUNTS:END -->';

  const block = [
    startMarker,
    `<!-- Auto-generated by scripts/counts.js — do not edit manually -->`,
    `<!-- Rules: ${counts.rules} | MCP Tools: ${counts.mcpTools} | Defense Layers: ${counts.layers} -->`,
    endMarker,
  ].join('\n');

  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);

  if (startIdx !== -1 && endIdx !== -1) {
    content = content.slice(0, startIdx) + block + content.slice(endIdx + endMarker.length);
  } else {
    // No markers yet — append before the closing </div> at the end.
    content = content.trimEnd() + '\n\n' + block + '\n';
  }

  fs.writeFileSync(readmePath, content);
}

// --- CLI ---
const args = process.argv.slice(2);
const counts = getCounts();

if (args.includes('--update-readme')) {
  updateReadme(counts);
  console.error('Updated README.md with counts block.');
}

console.log(JSON.stringify(counts, null, 2));