'use strict';

/*
 * VibeGuard Privacy Policy Generator.
 *
 * Analyzes the codebase and auto-generates a privacy policy based on:
 * - What PII is collected (forms, inputs, API params)
 * - Where data is stored (DB, cookies, localStorage)
 * - What third-party services are used (analytics, AI, error tracking)
 * - What consent mechanisms exist
 * - What data retention policies exist
 *
 * Generates a markdown privacy policy ready for legal review.
 *
 * 100% local. Zero network. Zero dependencies.
 */

const { auditPrivacy } = require('./privacy-audit');
const { auditNetwork } = require('./net-audit');

function generatePrivacyPolicy(dir, files) {
  const inv = auditPrivacy(dir, files);
  const net = auditNetwork(dir, files);

  const pii = inv.summary.piiFieldsDetected || [];
  const storage = inv.storage || [];
  const transmission = inv.transmission || [];
  const hasConsent = inv.summary.consentMechanisms > 0;
  const hasEncryption = inv.summary.encryptionPoints > 0;
  const hasRetention = inv.summary.retentionPolicies > 0;

  // Identify third-party services
  const thirdParty = new Set();
  for (const t of transmission) {
    if (t.type === 'Google Analytics') thirdParty.add('Google Analytics');
    if (t.type === 'Mixpanel') thirdParty.add('Mixpanel');
    if (t.type === 'Segment') thirdParty.add('Segment');
    if (t.type === 'PostHog') thirdParty.add('PostHog');
    if (t.type === 'Amplitude') thirdParty.add('Amplitude');
    if (t.type === 'Sentry') thirdParty.add('Sentry');
    if (t.type === 'Social tracking') thirdParty.add('Social Media Tracking (Facebook/Meta)');
    if (t.type === 'AI API') thirdParty.add('AI/LLM Provider (OpenAI/Anthropic/Google)');
  }

  // Identify storage types
  const storageTypes = new Set();
  for (const s of storage) {
    storageTypes.add(s.type);
  }

  const date = new Date().toISOString().slice(0, 10);

  let md = `# Privacy Policy\n\n`;
  md += `**Last updated: ${date}**\n\n`;
  md += `> This privacy policy was auto-generated by VibeGuard based on code analysis. It must be reviewed by a legal professional before publication.\n\n`;

  // Introduction
  md += `## 1. Introduction\n\n`;
  md += `This privacy policy describes how we collect, use, store, and protect your personal information when you use our application.\n\n`;

  // Information we collect
  md += `## 2. Information We Collect\n\n`;
  if (pii.length > 0) {
    md += `### Personal Information\n\n`;
    md += `We collect the following types of personal information:\n\n`;
    for (const field of pii) {
      md += `- ${field.replace(/_/g, ' ')}\n`;
    }
    md += `\n`;
  } else {
    md += `Based on our code analysis, we do not appear to collect personal information directly. If this is incorrect, please update this policy.\n\n`;
  }

  md += `### Automatically Collected Information\n\n`;
  md += `When you use our application, we may automatically collect:\n\n`;
  md += `- IP address (if logged)\n`;
  md += `- Browser type and version\n`;
  md += `- Device information\n`;
  md += `- Usage data and interactions\n`;
  if (thirdParty.size > 0) {
    md += `- Analytics data (see Section 4)\n`;
  }
  md += `\n`;

  // How we use information
  md += `## 3. How We Use Your Information\n\n`;
  md += `We use the information we collect to:\n\n`;
  md += `- Provide and maintain our service\n`;
  md += `- Respond to your requests and inquiries\n`;
  md += `- Improve our application and user experience\n`;
  if (thirdParty.has('AI/LLM Provider (OpenAI/Anthropic/Google)')) {
    md += `- Process your inputs through AI/LLM services to generate responses\n`;
  }
  if (thirdParty.has('Google Analytics') || thirdParty.has('Mixpanel') || thirdParty.has('Segment') || thirdParty.has('PostHog') || thirdParty.has('Amplitude')) {
    md += `- Analyze usage patterns and trends\n`;
  }
  md += `- Detect and prevent fraud or abuse\n`;
  md += `- Comply with legal obligations\n`;
  md += `\n`;

  // Third-party services
  md += `## 4. Third-Party Services\n\n`;
  if (thirdParty.size > 0) {
    md += `We use the following third-party services that may process your data:\n\n`;
    for (const tp of [...thirdParty].sort()) {
      md += `- **${tp}**: Used for ${tp.includes('Analytics') ? 'usage analytics' : tp.includes('Sentry') ? 'error monitoring' : tp.includes('AI') ? 'AI processing' : 'tracking'}. Their privacy policies apply to data they process.\n`;
    }
    md += `\n`;
    if (!hasConsent) {
      md += `> **WARNING (VibeGuard)**: No consent mechanism was detected in the code. Under GDPR/CCPA, you must obtain user consent before enabling third-party tracking.\n\n`;
    }
  } else {
    md += `Based on our code analysis, we do not use third-party tracking or analytics services.\n\n`;
  }

  // Data storage
  md += `## 5. Data Storage and Security\n\n`;
  if (storageTypes.size > 0) {
    md += `### Where We Store Data\n\n`;
    for (const st of storageTypes) {
      md += `- ${st}\n`;
    }
    md += `\n`;
  }
  if (hasEncryption) {
    md += `### Encryption\n\nWe use encryption to protect your personal information both in transit (HTTPS/TLS) and at rest.\n\n`;
  } else {
    md += `### Encryption\n\n> **WARNING (VibeGuard)**: No encryption was detected in the codebase. We recommend implementing encryption for personal data at rest and in transit.\n\n`;
  }
  md += `### Data Retention\n\n`;
  if (hasRetention) {
    md += `We retain personal data only as long as necessary for the purposes described in this policy or as required by law.\n\n`;
  } else {
    md += `> **WARNING (VibeGuard)**: No data retention policy was detected in the code. Under GDPR, you must define and implement data retention periods.\n\n`;
  }

  // Your rights
  md += `## 6. Your Privacy Rights\n\n`;
  md += `Depending on your location, you may have the following rights:\n\n`;
  md += `- **Right to access**: Request a copy of your personal data\n`;
  md += `- **Right to rectification**: Request correction of inaccurate data\n`;
  md += `- **Right to erasure**: Request deletion of your personal data ("right to be forgotten")\n`;
  md += `- **Right to restrict processing**: Request restriction of data processing\n`;
  md += `- **Right to data portability**: Request transfer of your data to another service\n`;
  md += `- **Right to object**: Object to processing of your data\n`;
  md += `- **Right to withdraw consent**: Withdraw consent at any time (if processing is based on consent)\n\n`;
  md += `To exercise these rights, contact us using the information in Section 8.\n\n`;

  // AI-specific disclosure
  if (thirdParty.has('AI/LLM Provider (OpenAI/Anthropic/Google)')) {
    md += `## 7. AI Data Processing\n\n`;
    md += `Our application uses AI/LLM services (such as OpenAI, Anthropic, or Google) to process user inputs. When you interact with our AI features:\n\n`;
    md += `- Your input text is sent to the AI provider for processing\n`;
    md += `- The AI provider processes your input on their servers\n`;
    md += `- We do not control the AI provider's retention of your input\n`;
    md += `- We recommend not sharing sensitive personal information (SSN, credit cards, health information) through AI features\n\n`;
    if (!inv.encryption.some(e => /redact|anonym|mask|scrub/i.test(e))) {
      md += `> **WARNING (VibeGuard)**: No PII redaction was detected before sending data to AI providers. We strongly recommend implementing PII redaction before AI API calls.\n\n`;
    }
  }

  // Contact
  md += `## 8. Contact Us\n\n`;
  md += `If you have questions about this privacy policy or want to exercise your privacy rights, contact:\n\n`;
  md += `- Email: [your-privacy-email@yourdomain.com]\n`;
  md += `- Address: [your business address]\n\n`;

  // Compliance notes
  md += `## 9. Compliance Notes\n\n`;
  md += `- **GDPR**: This policy is designed to comply with the EU General Data Protection Regulation.\n`;
  md += `- **CCPA**: This policy is designed to comply with the California Consumer Privacy Act.\n`;
  md += `- **COPPA**: If your application is directed at children under 13, additional compliance is required.\n\n`;

  // VibeGuard warnings
  const warnings = [];
  if (!hasConsent) warnings.push('No consent mechanism detected in code');
  if (!hasEncryption) warnings.push('No encryption detected in codebase');
  if (!hasRetention) warnings.push('No data retention policy detected in code');
  if (thirdParty.has('AI/LLM Provider (OpenAI/Anthropic/Google)')) warnings.push('Data sent to AI providers — verify PII redaction');

  if (warnings.length > 0) {
    md += `## 10. VibeGuard Audit Warnings\n\n`;
    md += `The following warnings were identified by VibeGuard's automated code analysis:\n\n`;
    for (const w of warnings) {
      md += `- ${w}\n`;
    }
    md += `\nThese warnings must be addressed before publishing this privacy policy.\n\n`;
  }

  md += `---\n\n`;
  md += `*This privacy policy was auto-generated by VibeGuard on ${date}. It must be reviewed by a qualified legal professional before publication.*\n`;

  return md;
}

function generateCSP(dir, files) {
  const fs = require('fs');
  const path = require('path');

  const sources = {
    'default-src': ["'self'"],
    'script-src': ["'self'"],
    'style-src': ["'self'"],
    'img-src': ["'self'", 'data:', 'https:'],
    'font-src': ["'self'", 'https://fonts.gstatic.com'],
    'connect-src': ["'self'"],
    'frame-src': ["'none'"],
    'object-src': ["'none'"],
    'base-uri': ["'self'"],
    'form-action': ["'self'"],
    'upgrade-insecure-requests': [],
  };

  const externalDomains = new Set();

  for (const file of files) {
    let content;
    try { content = fs.readFileSync(file, 'utf8'); } catch { continue; }

    // Find external script/style sources
    let m;
    const scriptRe = /<script\s+src\s*=\s*['"]https?:\/\/([^'"/]+)/gi;
    while ((m = scriptRe.exec(content)) !== null) {
      externalDomains.add(m[1]);
      sources['script-src'].push(`https://${m[1]}`);
    }

    const styleRe = /<link\s+[^>]*href\s*=\s*['"]https?:\/\/([^'"/]+)/gi;
    while ((m = styleRe.exec(content)) !== null) {
      sources['style-src'].push(`https://${m[1]}`);
    }

    const imgRe = /src\s*=\s*['"]https?:\/\/([^'"/]+)/gi;
    while ((m = imgRe.exec(content)) !== null) {
      if (!m[1].includes('localhost') && !m[1].includes('127.0.0.1')) {
        sources['img-src'].push(`https://${m[1]}`);
      }
    }

    // Find API endpoints
    const apiRe = /fetch\s*\(\s*['"]https?:\/\/([^'"/]+)/gi;
    while ((m = apiRe.exec(content)) !== null) {
      if (m[1] !== 'localhost' && m[1] !== '127.0.0.1') {
        sources['connect-src'].push(`https://${m[1]}`);
      }
    }

    // Check for inline scripts (dangerous)
    if (/<script[^>]*>[^<]+/i.test(content) && !/<script[^>]*src\s*=/i.test(content)) {
      sources['script-src'].push("'unsafe-inline'");
    }

    // Check for inline styles
    if (/<style[^>]*>/i.test(content)) {
      sources['style-src'].push("'unsafe-inline'");
    }
  }

  // Remove duplicates
  for (const key of Object.keys(sources)) {
    sources[key] = [...new Set(sources[key])];
  }

  // Build CSP string
  const parts = [];
  for (const [key, vals] of Object.entries(sources)) {
    if (vals.length === 0 && key === 'upgrade-insecure-requests') {
      parts.push(key);
    } else if (vals.length > 0) {
      parts.push(`${key} ${vals.join(' ')}`);
    }
  }

  const csp = parts.join('; ');
  const helmet = `// Express/Helmet:\napp.use(helmet.contentSecurityPolicy({\n  directives: ${JSON.stringify(sources, null, 2).replace(/"/g, "'").replace(/'/g, '"').replace(/\n/g, '\n  ')}\n}));`;

  return {
    csp,
    helmet,
    sources,
    warnings: [
      sources['script-src'].includes("'unsafe-inline'") ? "CSP includes 'unsafe-inline' for scripts — remove inline scripts" : null,
      sources['script-src'].includes("'unsafe-eval'") ? "CSP includes 'unsafe-eval' — remove eval() usage" : null,
    ].filter(Boolean),
  };
}

module.exports = { generatePrivacyPolicy, generateCSP };